var constants = {
    gameName: "HANGMAN",
    whiteColor: "#ffffff",
    menuCategoriesName: "Select category:",
    buttonImageName: "button",
    bigText: 30,
    smallText: 16,
    firstMenuButton: 80,
    menuCategoryCoordinate: 40,
    buttonTextModifier: 5,
    buttonModifier: 50,
    gameStateName: "GameState",
    menuStateName: "MenuState",
    youWinText:"YOU WIN!",
    youLoseText: "YOU LOSE!",
    newGameText: "New Game",
    newGameButtonCoordinate: 200,
    playedGamesText: "Played Games: ",
    wonGamesText: "Won Games: ",
    wonGamesCoordinate: 20,
    lostGamesText: "Lost Games: ",
    lostGamesCoordinate: 40,
    guessedLettersText: "Guessed Letters: ",
    guessedLettersCoordinate: 60,
    guessedWordsText: "Guessed Words: ",
    guessedWordsCoordinate: 80,
    wrongLettersText: "Wrong Letters: ",
    wrongLettersCoordintates: 200,
    resultTextCoordinate: 150,
    displayedWordCoordinate: 264,
    descriptionCoordinate: 300,
    localStorageStatsName: "stats",
    guessWordText: "Guess Word",
    guessWordX: 550,
    guessWordY: 40,
    enterKey: 13,
    aKey: 65,
    zKey: 90,
    maxErrors: 5,
    messageCoordinates: 240,
    messageTimerTime: 3000,
    triedLetterMessage: "You already tried this letter",
    alphabetButtonsX: 480,
    alphabetButtonsY: 120,
    alphabetButtonModifier: 30,
    alphabetButtonTextModifier: 4,
    alphabetRowModifier: 5
}